// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://goklczyiriiiouorngov.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdva2xjenlpcmlpaW91b3JuZ292Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MzQyOTUsImV4cCI6MjA2MDMxMDI5NX0.CMYW-VYwPXlUzO6TtFlA1rQoveDdCgog5Dkv-aVUHoY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);